project:
  type: website
  # type: confluence

resources:
  - CNAME

render:
  - "!*.ipynb_checkpoints"

website:
  site-url: "https://docs.mlerp.cloud.edu.au/"
  title: "MLeRP User Guide Documentation"
  favicon: ./images/favicon-32x32.png
  navbar:
    logo: ./images/mstile-150x150.png
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - faq.qmd
    right:
      - text: Log in
        href: https://mlerp.cloud.edu.au/launch
      - text: Sign up
        href: https://forms.gle/HuPk8ckmptq2LCaR7
      - icon: github
        href: https://github.com/mitchellshargreaves-monash/MLeRP-Documentation
        aria-label: Documentation
      - icon: rss
        href: https://docs.mlerp.cloud.edu.au/release.xml
        aria-label: Release Notes
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - compute.qmd
      - faq.qmd
      - section: "Applications"
        contents:
        - auto: "applications/*"
      - section: "Connecting"
        contents:
        - auto: "connecting/*.qmd"
      - section: "Tutorials"
        contents:
        - auto: "tutorials/*"
      - file: release.qmd

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    css: styles.css
    toc: true