project:
  type: website
  # type: confluence

website:
  title: "MLeRP User Guide Documentation"
  favicon: ./images/favicon-32x32.png
  navbar:
    logo: ./images/mstile-150x150.png
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - faq.qmd
    right:
      - text: Log in
        href: https://mlerp.cloud.edu.au/launch
      - text: Sign up
        href: https://forms.gle/p9HWS79yxDouP6Tu8
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - compute.qmd
      - faq.qmd
      - section: "Applications"
        contents:
        - auto: "applications/*"
      
      - section: "Connecting"
        contents:
        - auto: "connecting/*.qmd"
      - section: "Tutorials"
        contents:
        - auto: "tutorials/*"

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    css: styles.css
    toc: true