project:
  type: website

website:
  title: "MLeRP User Guide Documentation"
  favicon: ./images/favicon-32x32.png
  navbar:
    logo: ./images/mstile-150x150.png
    left:
      - text: "Home"
        file: index.qmd
      - faq.qmd
      - about.qmd
    right:
      - text: Log in
        href: https://mlerp.cloud.edu.au/launch
      - text: Sign up
        href: https://forms.gle/p9HWS79yxDouP6Tu8
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - faq.qmd
      - text: VS Code
        file: vscode.qmd
      - dask-slurm.ipynb
      - dask-pytorch.ipynb

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    css: styles.css
    toc: true